// Domain types are defined in their respective files.
// Re-export everything from api for convenient single-import access.
export type {
  Song,
  SongArtist,
  SongAlbum,
  SongUrl,
  LyricLine,
  LyricSyllable,
  LyricData,
  Artist,
  ArtistDetail,
  Album,
  MV,
  Playlist,
  Comment,
  CommentUser,
  CommentResponse,
  User,
  UserProfile,
  UserAccount,
  LoginQRKey,
  LoginQRCreate,
  QRStatus,
} from './api'

export type {
  ApiResponse,
  PaginatedParams,
  PaginatedResponse,
  SongDetailResponse,
  LyricDataResponse,
  SimiSongResponse,
  PlaylistDetailResponse,
  PlaylistTrackResponse,
  HotSearchItem,
  HotSearchResponse,
  LoginCellphoneResponse,
  LikelistResponse,
  UserRecordItem,
  UserRecordResponse,
  UserCloudItem,
  UserCloudResponse,
  UserDetailResponse,
  UserPlaylistResponse,
  PersonalFMResponse,
  ArtistDetailResponse,
  ArtistAlbumResponse,
  MVDetailResponse,
  MVDetailInfoResponse,
  SimiMvResponse,
  ToplistResponse,
  TopListResponse,
  SearchResponse,
  SearchType,
  SearchTypeValue,
  PlayMode,
} from './api'
